### ISSUE TITLE
AirSimEnv-v42

### ISSUE THREAD

**Issue by AloshkaD** [Kjell-K/AirGym#5]
@Kjell-K Thanks for sharing the repo. I keep getting the error below although gym works for me on other examples
```
Traceback (most recent call last):
  File "DQN-Train.py", line 39, in <module>
    env = gym.make(args.env_name)
  File "C:\Users\A\AppData\Local\conda\conda\envs\tf\lib\site-packages\gym\envs\registration.py", line 167, in make
    return registry.make(id)
  File "C:\Users\A\AppData\Local\conda\conda\envs\tf\lib\site-packages\gym\envs\registration.py", line 118, in make
    spec = self.spec(id)
  File "C:\Users\A\AppData\Local\conda\conda\envs\tf\lib\site-packages\gym\envs\registration.py", line 153, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: AirSimEnv-v42
```

**Comment by deyaa97** [comment]
Hello, could you solve this problem?
I am running the code and having the same isuue you had.

Thanks.

**Comment by WayneHsiao0225** [comment]
@AloshkaD @deyaa97 
I  run the code and have the same issue.

> /usr/bin/python3.8 /home/c95hyw/PycharmProjects/GOD/GOD/AirGym_mutirotor/DQN-Train.py
> 2020-09-21 15:36:37.876825: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/dist-packages/gym/envs/registration.py", line 121, in spec
>     return self.env_specs[id]
> KeyError: 'AirSimEnv-v42'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/c95hyw/PycharmProjects/GOD/GOD/AirGym_mutirotor/DQN-Train.py", line 45, in <module>
>     env = gym.make(args.env_name)
>   File "/usr/local/lib/python3.8/dist-packages/gym/envs/registration.py", line 145, in make
>     return registry.make(id, **kwargs)
>   File "/usr/local/lib/python3.8/dist-packages/gym/envs/registration.py", line 89, in make
>     spec = self.spec(path)
>   File "/usr/local/lib/python3.8/dist-packages/gym/envs/registration.py", line 131, in spec
>     raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
> gym.error.UnregisteredEnv: No registered env with id: AirSimEnv-v42
> 
> Process finished with exit code 1

Could you solve this problem?
Thanks you.

**Comment by Moj-Dev** [comment]
Hi, could you solve this problem?
I have the same problem
