### ISSUE TITLE
citation on project

### ISSUE THREAD

**Issue by gonzaloaguilarjimenez** [Kjell-K/AirGym#8]
@Kjell-K 

Sorry for contacting you here.

I am using your work for a project. How would you like it to be cited? 

Thanks.

**Comment by Kjell-K** [comment]
There is a paper on this project to cite: https://www.semanticscholar.org/paper/Self-training-by-Reinforcement-Learning-for-Drones-Kersandt-Mu%C3%B1oz/859f8d5c7e00ec03fe120085d2a4c133e98a5caa
